### ISSUE TITLE
Update the plugin

### ISSUE THREAD

**Issue by mihai-vlc** [kemayo/sublime-text-2-goto-documentation#36]
Hello,
first of all thank you for this plugin it works grate.
However not everybody uses the same docs, and I found myself in the past having to clone and maintain my own version of this plugin witch is fine but I think we can do better.

I made a few changes here: https://github.com/ionutvmi/GotoDocumentation

Basically it allows the end user to use whatever docs he wants (local or remote).
They can do that by keeping a settings file.
I will continue to maintain that version  however I don't see the point in having 2 plugins that do the same thing and I would like to merge it with this one to have it available in the package control also.

Because the changes are quite large I haven't made a pull request yet and changed the name of the plugin.

If you like it and you would like to merge it let me know and I will make a pull request.

**Comment by kemayo** [comment]
I generally support merging this in.

However, I do have a concern about the use of settings for the documentation definitions... Sublime doesn't merge the contents of keys, so the user has to copy the entire `docs` object into their own preferences if they just want to add a single new documentation type, and that then cuts them off forever from new documentation definitions being added to the core package. It'd make more sense to maintain the core documentation and user-extendable documentation separately. Probably put the core docs just as a dictionary in Python, and merge with the settings key when needed. (That'd preserve the ability to add new types, and to disable existing core types by just putting in a `"css": false`.)

Additionally, trying to view some python documentation caused this error: `FileNotFoundError: [Errno 2] No such file or directory: 'python -m pydoc class'`. I'd suspect this is because you're not splitting the command up before passing it to subprocess, so it's literally trying to execute the (non-existent) file 'python -m pydoc class'

**Comment by mihai-vlc** [comment]
Hi, 
thank you for your suggestions.
I will review them and open a pull request as soon as I can.

**Comment by mihai-vlc** [comment]
I have added a pull request here https://github.com/kemayo/sublime-text-2-goto-documentation/pull/37
